### ISSUE TITLE
[Request] Update library dependency

### ISSUE THREAD

**Issue by pphu** [lob/lob-java#105]
I would like to request Ning's async-http-client V1.8.15 be updated to a more recent version. My current project uses another library with a dependency on async-http-client V1.9.39 and caused a conflict as some of the classes paths have changed between the two major versions. 

The current workaround I have is to use https://github.com/AsyncHttpClient/async-http-client, where the package names are different and do not conflict. 

However I now have two different version of async-http-client and two different version of netty.

**Comment by dmlittle** [comment]
Hi @pphu, thanks for brining up this issue. We'll work on upgrading our wrapper dependencies to their latest versions.

**Comment by dmlittle** [comment]
@pphu unfortunately we are not able to upgrade to async-http-client v1.9.39 at this time as it drops support for Java 5 & 6. There is currently a branch [upgrade_ning](https://github.com/lob/lob-java/tree/upgrade_ning) that has the updated library if you're interested in downloading and building the JAR yourself but we're not merging it into master just yet.
