### ISSUE TITLE
Error creating a LobClient

### ISSUE THREAD

**Issue by albertoortiz** [lob/lob-java#113]
This is the error I got it:
java.lang.NoClassDefFoundError: Fatal execution error, caused by com/ning/http/client/Part

I am using Scala 2.11.8 and JVM 1.8

The error is thrown when 
val  client = AsyncLobClient.createDefault(apiKey)

**Comment by albertoortiz** [comment]
We are also using playframework 2.4, I am wondering if there is a problem between the async-http client and the netty version running under play ....

**Comment by dmlittle** [comment]
Hi @albertoortiz,

What version of `lob-java` are you using? The issue might stem from a different `async-http-client` or `netty` versions running under the `play` and `lob-java` libraries. Do you know what version of `async-http-client` or `netty` the play framework is using (I'm not familiar with it)? 

Donald

**Comment by dmlittle** [comment]
I'll be closing this issue as we haven't heard back from you. Feel free to reach out to us at support@lob.com if you run into any issues.
