### ISSUE TITLE
Access to Components object from USVerificationResponse

### ISSUE THREAD

**Issue by cbarroetam** [lob/lob-java#117]
Currently the example of usage  for the `verifyUSAddress` method, does not include a properly way to extract the values from the `Components` object, which is embedded into the `USVerificationResponse` and that class, `Components` is marked as private.  Is there any way using the current API to access information such as: city, zipcode, state and so on?

**Comment by dmlittle** [comment]
@cbarroetam thanks for reporting this issue. I'll work on making them public so you can easily access them.

**Comment by cbarroetam** [comment]
@dmlittle thank you.

**Comment by dmlittle** [comment]
@cbarroetam a new version of the wrapper was just cut and deployed making these classes public. You should be able to retrieve the information directly from the `USVerificationResponse` (example below). The new version of the wrapper (6.0.1) should appear on Maven in a little bit.

```java
final USVerificationRequest request = USVerificationRequest.builder()
    .primary_line("185 BERRY ST")
    .secondary_line("STE 6600")
    .city("SAN FRANCISCO")
    .state("CA")
    .zipCode("94107")
    .build();

USVerificationResponse response = client.verifyUSAddress(request).get();
    
// Primary Number
System.out.println(response.getComponents().getPrimaryNumber());    
```
