### ISSUE TITLE
Java 8 Support

### ISSUE THREAD

**Issue by codylerum** [lob/lob-java#131]
Drop Joda-Time in favor of standard JSR 310 Date Time API

The upcoming AWS v2 JDK is doing the same.

**Comment by dmlittle** [comment]
Hi @codylerum, I think migrating over to the new `java.time` (JSR 310) makes sense. Thanks for putting up #132 with the changes required to migrate over. I'll take a look at it over the coming days.

**Comment by codylerum** [comment]
This was merged
