### ISSUE TITLE
Provide a way to deserialize a webhook event

### ISSUE THREAD

**Issue by codylerum** [lob/lob-java#133]
Stripe for instance provides something like 

`Event event = Webhook.constructEvent(payload);`

Where payload is the raw json string

**Comment by dmlittle** [comment]
Hi @codylerum, currently the webhook and event endpoints are not documented for public use and therefore not supported by our libraries. In the event we make these public, we'll be sure to add them.

**Comment by codylerum** [comment]
@dmlittle https://lob.com/docs#events

What am I missing here? The webhooks are easy to setup and define.

**Comment by dmlittle** [comment]
@codylerum that's our documentation for our webhook events and what you can expect from our webhook requests but there are no public endpoints for you to retrieve or list events for a particular resource (postcards, letter, check, etc.). What's the use case you're thinking of?

**Comment by codylerum** [comment]
I'm referring to reading the event that is sent by lob on my side. Sent to me via the web hook.

**Comment by codylerum** [comment]
@dmlittle So for example I threw the code that I have to "read" a webhook that is sent from lob to me.

https://github.com/codylerum/lob-java/commit/efb50ce4f988f2240eca840042b7fda5b250d17b

This code lets me deserialize a webhook from lob and determine the id and type of the event.

JAX-RS code.

```
@Path("/lob")
public class LobRest {

    static final Logger log = Logger.getLogger(LobRest.class);

    @Inject
    private QueuedEmailUtil queuedEmailUtil;

    @Path("webhook")
    @POST
    @Consumes(MediaType.APPLICATION_JSON)
    public Response webhook(String payload) throws IOException {
        Event event = Webhook.constructEvent(payload);
        log.infof("Procesing %s for %s", event.getEvent_type().getId(), event.getReference_id());      

        //Other logic here.

        return Response.ok().build();
    }
}
```

My code doesn't have support for readying the "body" object of the event as that looks like a fun Jackson polymohic mapping which is beyond my Jackson experience.

**Comment by dmlittle** [comment]
@codylerum this makes sense. I'll look into getting this feature into the library in the near future. I'll re-open this ticket and post an update here when a new version of the library with this functionality has been released.

**Comment by codylerum** [comment]
👍

**Comment by merzbird** [comment]
@dmlittle Is there any progress or estimated release date? Thanks.
