### ISSUE TITLE
Provide Support for Custom HTTP Endpoints

### ISSUE THREAD

**Issue by fr-kirankshatriya** [lob/lob-java#141]
Can you provide support for custom HTTP endpoints so we can mock the service?

**Comment by marklee22** [comment]
@fr-kirankshatriya Could you elaborate a little more on what you're trying to do?

**Comment by fr-kirankshatriya** [comment]
Sure. Sorry.  I wanted to test my client code by mocking the lob service with Wiremock but, I dont see an easy way to provide a different base endpoint URL i.e., base endpoint for my Wiremock service.

I've actually decided to just use the lob service directly with a Test key since the test requests are free.  That does make testing things like Rate Limiting tricky, if not possible.

**Comment by marklee22** [comment]
I see. So you want to run an integration test that has the lob library making requests to whatever web server you have setup instead of hitting our API directly?

Is mockito/easymock a possible alternative to mock out each Lob call?

**Comment by fr-kirankshatriya** [comment]
I dont think so.  The method i'm testing makes the following call.  I cant mock Letter.RequestBuilder because it is a final class.  I could create some sort of wrapper class; it's not the cleanest thing though.

`			
LobResponse<Letter> response = new Letter.RequestBuilder()
    .setAddressPlacement(addressPlacement)
    .setColor(color)
    .setDoubleSided(doubleSided)
    .setFile(message)
    .setFrom(from)
    .setMailType(mailType)
    .setMetadata(metadata)
    .setReturnEnvelope(returnEnvelope)
    .setTo(to)
    .create(requestOptionsBuilder.setIdempotencyKey(id).build());
`

**Comment by SidneyAllen** [comment]
@fr-kirankshatriya - sorry we left this issue open for so long.  We are reviewing them to determine if the issue has been resolved. 

Looking at our PR history we see that proxying was added in Oct 2018.  Wondering if this resolved this issue for you?
https://github.com/lob/lob-java/pull/145

Let us know
