### ISSUE TITLE
java.lang.NoSuchMethodError: No static method encodeBase64String

### ISSUE THREAD

**Issue by dbogoslovtsev** [lob/lob-java#157]
I'm getting a NoSuchMethodError while using on Android
`java.lang.NoSuchMethodError: No static method encodeBase64String([B)Ljava/lang/String; in class Lorg/apache/commons/codec/binary/Base64; or its super classes (declaration of 'org.apache.commons.codec.binary.Base64' appears in /system/framework/org.apache.http.legacy.jar)`
in ResponseGetter line 78.
I suppose you should use encodeToString() method instead

**Comment by ShariqT** [comment]
Thank you for raising this issue.  If I am interpreting the error correctly, the error is being thrown on Android in the ResponseGetter class line 78.  This is where we set the authorization header and encode the Lob API keys.  

I am assuming you are using the address verification endpoints and publishable keys as your API keys are stored in the client.

Please let us know if you resolved this issue.

We are actively working on new SDKs which will be generated from our API specifications and will fold this feedback into our test plans.
