### ISSUE TITLE
US Verification missing Consistency Score

### ISSUE THREAD

**Issue by danieltruonghatch** [lob/lob-java#174]
Attempted to utilize the Lob Java SDK in order to run US Verification on certain addresses. However, some fields in the response was missing, especially `lob_consistency_score`. 

https://docs.lob.com/#operation/us_verification

**Comment by tomas-peirotti-ahead** [comment]
If you mean the `lob_confidence_score`, I have the same issue. The API responds it, but the Java SDK doesn't map it.

**Comment by ShariqT** [comment]
I'll take a look into this and make sure we are reflecting all of the fields in the API.

**Comment by BennyKitchell** [comment]
We have added `lob_confidence_score` to the response and it has been released with version `12.3.6`. Thanks for catching this and if you find any other inconsistencies, please let us know!
