### ISSUE TITLE
Bump to JDK 8 Minimum

### ISSUE THREAD

**Issue by codylerum** [lob/lob-java#199]
Can we get a bump to JDK 8 for version 13?

I'm really not thrilled in pulling in the three ten backport library to support Dates and Times when JDK 8 was released 8 years ago

Other large libraries such as Stripe and Twilio have already taken these steps and require JDK8+

https://github.com/stripe/stripe-java
https://github.com/twilio/twilio-java

**Comment by codylerum** [comment]
This is actually a regression. The v12 version of the libary was at JDK 8 using JSR310

https://github.com/lob/lob-java/pull/132

**Comment by BennyKitchell** [comment]
@codylerum This shouldn't be an issue, just compiled with Java 13 and had minimal changes. So I will put together and release a new version tomorrow with this change. (I will of course update this issue when that is done). Thanks!

**Comment by codylerum** [comment]
Sounds good. My only need is getting to use native JSR 310 Date/Time so we don't have to bring in the legacy backport library.

**Comment by BennyKitchell** [comment]
@codylerum  I will be releasing this version Monday morning and will update this issue when it has propagated to maven correctly.

**Comment by BennyKitchell** [comment]
@codylerum  As discussed this has been released, I will be leaving your other issue open until we add the necessary methods discussed. But this release [13.2.0](https://search.maven.org/artifact/com.lob/lob-java/13.2.0/jar), does bump the java version and use the native DateTime. Thanks!
