### ISSUE TITLE
UsComponents.CarrierRouteTypeEnum is missing an enum

### ISSUE THREAD

**Issue by AdityaZagadeCT** [lob/lob-java#331]
In the response below, carrier_route_type -> contract, but CarrierRouteTypeEnum does not contain an enum. 

1. Should a new enum is added or HIGHWAY_CONTRACT("highway_contract") should be changed to HIGHWAY_CONTRACT("contract") ?

2. https://docs.lob.com/#tag/US-Verification-Types, LOOK for 'Carrier Route Types ', as per the doc, "contract" is an unexpected value for 'carrier_route_type'

{
  "id": "us_ver_1b251fce64XXXXXXXXXX",
  "recipient": "",
  "primary_line": "14664 XXXXXXXXX",
  "secondary_line": "",
  "urbanization": "",
  "last_line": "ORO XXXXXXXXX",
  "deliverability": "deliverable",
  "valid_address": true,
  "components": {
    "primary_number": "14664",
    "street_predirection": "",
    "street_name": "MARIGOLD",
    "street_suffix": "RD",
    "street_postdirection": "",
    "secondary_designator": "",
    "secondary_number": "",
    "pmb_designator": "",
    "pmb_number": "",
    "extra_secondary_designator": "",
    "extra_secondary_number": "",
    "city": "ORO GRANDE",
    "state": "CA",
    "zip_code": "92368",
    "zip_code_plus_4": "9553",
    "zip_code_type": "standard",
    "delivery_point_barcode": "923689553640",
    "address_type": "residential",
    "record_type": "street",
    "default_building_address": false,
    "county": "SAN BERNARDINO",
    "county_fips": "06071",
    "carrier_route": "H001",
    "carrier_route_type": "contract",
    "latitude": 34.669959,
    "longitude": -117.34347
  },
  ....
}

Unexpected value 'contract'","className":"java.lang.IllegalArgumentException","errorMessages":null,"stackTraceElements":"java.lang.IllegalArgumentException: Unexpected value 'contract'
 com.lob.model.UsComponents$CarrierRouteTypeEnum.fromValue(UsComponents.java:795)
 com.lob.model.UsComponents$CarrierRouteTypeEnum$Adapter.read(UsComponents.java:807)
 com.lob.model.UsComponents$CarrierRouteTypeEnum$Adapter.read(UsComponents.java:798)
 com.google.gson.TypeAdapter$1.read(TypeAdapter.java:199)
 com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:161)
 com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:266)
 com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:161)
 com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:266)
 com.google.gson.Gson.fromJson(Gson.java:1058)
 com.google.gson.Gson.fromJson(Gson.java:1016)
 com.google.gson.Gson.fromJson(Gson.java:959)
 com.lob.api.JSON.deserialize(JSON.java:146)
 com.lob.api.ApiClient.deserialize(ApiClient.java:821)
 com.lob.api.ApiClient.handleResponse(ApiClient.java:1029)
 com.lob.api.ApiClient.execute(ApiClient.java:951)
 com.lob.api.client.UsVerificationsApi.verifySingleWithHttpInfo(UsVerificationsApi.java:295)
 com.lob.api.client.UsVerificationsApi.verifySingle(UsVerificationsApi.java:270)

**Comment by BennyKitchell** [comment]
Hi @AdityaZagadeCT, 

Thanks for the feedback. Just so I can understand , what is the argument for changing `highway contract` to `contract`?
As we already have the enum for highway contract represented [here](https://github.com/lob/lob-java/blob/main/src/main/java/com/lob/model/UsComponents.java#L766).

**Comment by AdityaZagadeCT** [comment]
Hi @BennyKitchell , 
I am not suggesting that highway_contract be changed to contract, is the right fix. In the response we got value for 'carrier_route_type' as 'contract', which is not present in your ENUM list.

**Comment by AdityaZagadeCT** [comment]
Solution:

public enum CarrierRouteTypeEnum {
    CITY_DELIVERY("city_delivery"),
    
    RURAL_ROUTE("rural_route"),
    
    HIGHWAY_CONTRACT("highway_contract"),

    CONTRACT("contract"),
    
    PO_BOX("po_box"),
    
    GENERAL_DELIVERY("general_delivery"),
    
    EMPTY("");
 .......

**Comment by BennyKitchell** [comment]
@AdityaZagadeCT  We made a change to our internal systems, everything should be working for you now. No update to the Java SDK is needed. Please let me know if this has fixed the issue for you. Thanks!

**Comment by AdityaZagadeCT** [comment]
Thanks, the issue is fixed now.
