### ISSUE TITLE
Build failing due to maven clean

### ISSUE THREAD

**Issue by mgartner** [lob/lob-java#37]
All the tests pass, but this command is exiting with code 1, causing the build to fail:

```
mvn clean package jacoco:report coveralls:jacoco
```

**Comment by leore** [comment]
is that the correct way to call coveralls for java

**Comment by javadev** [comment]
There are no errors for me:

[INFO] Successfully wrote Coveralls data in 237ms
[INFO] Gathered code coverage metrics for 33 source files with 1276 lines of code:
[INFO] - 225 relevant lines
[INFO] - 224 covered lines
[INFO] - 1 missed lines
[INFO] Submitting Coveralls data to API
[INFO] Successfully submitted Coveralls data in 3214ms for Job #97.1
[INFO] https://coveralls.io/jobs/4382652
[INFO] *** It might take hours for Coveralls to update the actual coverage numbers for a job
[INFO]     If you see question marks in the report, please be patient
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1:24.866s
[INFO] Finished at: Tue Feb 10 11:05:54 EET 2015
[INFO] Final Memory: 33M/491M
[INFO] ------------------------------------------------------------------------

**Comment by javadev** [comment]
We can point out coverals to the lob account, not javedev.
I will prepare a pull request.

**Comment by javadev** [comment]
` mvn clean package jacoco:report` is enough, I think

**Comment by javadev** [comment]
This issue may be closed. All maven task work for me.
