### ISSUE TITLE
Missing Credentials for lob.com

### ISSUE THREAD

**Issue by pon** [lob/lob-java#43]
Hey @javadev since you did the inital push to the central repository do you have the relevant credentials for doing future releases?

**Comment by javadev** [comment]
Yes, I have a login/password for oss.sonatype and valid public key to sign jar and pom files.

**Comment by pon** [comment]
In the short term can you push the master branch as version 2.0.0? 

We're a bit inexperienced with java here - could you lay out the path to us being able to submit new versions as well?

**Comment by javadev** [comment]
Yes, I can publish master branch as version 2.0. First you need to register a new user in oss sonatype, then create a public key, create a bundle and publish it via browser.

**Comment by javadev** [comment]
Released as:

  <groupId>com.lob</groupId>
  <artifactId>lob-java</artifactId>
  <version>2.0.0</version>

**Comment by pon** [comment]
Should I be seeing a change here? 

https://search.maven.org/#search%7Cga%7C1%7Ca%3A%22lob-java%22

**Comment by javadev** [comment]
Maven search will be updated soon :)
![lob_version_2_0](https://cloud.githubusercontent.com/assets/348496/8193261/76ed72ac-147c-11e5-8bd3-fdb754ff547d.PNG)

**Comment by javadev** [comment]
Maven search works for me.

**Comment by javadev** [comment]
@pon Do we need a new version in maven central repository?

**Comment by pon** [comment]
We will - there a 2-3 more PRs that will come in this week as well

**Comment by javadev** [comment]
Version 2.0.2 was deployed to the maven central repository. Issue may be closed.

**Comment by javadev** [comment]
!

**Comment by leore** [comment]
Hey @javadev can you email us the credentials to engineering@lob.com

**Comment by javadev** [comment]
I requested permission to create artifacts with help of jira issue. You may request access to your credentials, I think. https://issues.sonatype.org/plugins/servlet/mobile#issue/OSSRH-12963

**Comment by leore** [comment]
@dmlittle @mgartner

**Comment by javadev** [comment]
Good! We have two persons to ask permissions in OSS. Issue may be closed.

**Comment by leore** [comment]
@javadev What does that mean? We do not have the credentials. We need them. Please email us at engineering@lob.com

**Comment by javadev** [comment]
I used this guide to create a credentials in OSS: http://central.sonatype.org/pages/ossrh-guide.html
Have you try it?

**Comment by javadev** [comment]
@leore Why do you need my credentials for OSS?

**Comment by mgartner** [comment]
@javadev thanks. Working to get access now.

**Comment by javadev** [comment]
Good. Have a nice request processing.

**Comment by javadev** [comment]
I see version 2.1.0 in central maven repository! Issue may be closed.

**Comment by dmlittle** [comment]
@javadev Thanks for all the help!
