### ISSUE TITLE
Add Coveralls Badge

### ISSUE THREAD

**Issue by pon** [lob/lob-java#45]

**Comment by javadev** [comment]
What is token for coverals lob-java project?

**Comment by pon** [comment]
@eanderle - did you add the project to coveralls?

**Comment by eanderle** [comment]
I copied the coveralls data from the old project, which points to @javadev's coveralls account. Lob should update `pom.xml` with the API token for the Lob account.

**Comment by javadev** [comment]
I can change coverals repository by replacing token in pom.xml.

**Comment by javadev** [comment]
Pull request was created.
