### ISSUE TITLE
Make sure description is being used, not name

### ISSUE THREAD

**Issue by robinjoseph08** [lob/lob-java#56]
I know for jobs, the builder has a `.name` function, but no `.description` function and this 422s with an api key on the newer version. This might be the case for other endpoints as well.

**Comment by javadev** [comment]
I will add description to the job;s builder

**Comment by javadev** [comment]
@robinjoseph08 Could you check jobs request again, please?

**Comment by robinjoseph08** [comment]
It looks like the builder is fine, but the response wasn't parsing description. I believe @dmlittle is taking care of it though. :+1:

**Comment by javadev** [comment]
Looks like description parsing in response was added with version 2.0.2. Issue may be closed.

**Comment by javadev** [comment]
!

**Comment by javadev** [comment]
!
