### ISSUE TITLE
Unit test error bank_address is required

### ISSUE THREAD

**Issue by javadev** [lob/lob-java#82]
testCreateBankAccount(com.lob.client.test.BankAccountTest)  Time elapsed: 0.141 sec  <<< ERROR!
java.util.concurrent.ExecutionException: LobApiException: https://api.lob.com/v1/bank_accounts 422: bank_address is required

**Comment by javadev** [comment]
Looks like it was fixed, but not released

**Comment by robinjoseph08** [comment]
Thanks for the heads up! I'll be releasing it soon!

**Comment by javadev** [comment]
Ok, good
